### ISSUE TITLE
show-authorization, authorization-status

### ISSUE THREAD

**Issue by vongohren** [trello/power-up-template#2]
These are two capabilities that are not documented at all! Im trying to create a power up now, but when I add these capabilities, my settings wont work. I want the user to click settings and then auth himself first, without clicking settings and so forth. How can I cat auth in the settings?

These capabilites is used but slack and github forexample

**Comment by mpcowan** [comment]
@Snorlock Good catch, we don't have those documented yet. We'll get that fixed. In the meantime, here is what you are looking for:

``` javascript
TrelloPowerUp.initialize({
  'authorization-status': (t) =>
    // return a promise that resolves to the object with
    // a property 'authorized' being true/false
    new TrelloPowerUp.Promise((resolve) => resolve({ authorized: false })),
  'show-authorization': (t) =>
    // return what to do when a user clicks the 'Authorize Account' link
    // from the Power-Up gear icon which shows when 'authorization-status'
    // returns { authorized: false }
    // in this case we will open a popup
    t.popup({
      title: 'My Auth Popup',
      url: 'authorize.html',
      height: 140,
    }),
});
```

Additionally you'll need to add those two capabilities to the capabilities section of your manifest as well to get it to work.

**Comment by vongohren** [comment]
Thx @mpcowan, works well!

**Comment by bentleycook** [comment]
Adding documentation here: https://github.com/trello/api-docs/pull/43
